version: "3.9"
#criando os containers do banco de dados e da aplicação web
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: workout
    ports:
      - "5433:5432"
      #garantindo persistencia dos dados
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      #conexão com o banco de dados
    environment:
      DATABASE_URL: postgresql://postgres:senha123@db:5432/workout


volumes:
  postgres_data:
